[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm install --production=false --frozen-lockfile=false"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "npm run start:railway"
