name: Mirror to Public

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # OPTIONAL: Remove or rewrite files that must never go public
      - name: Strip private files before publish
        run: |
          rm -f .env .env.local .env.* config/local.json
          rm -rf secrets/ data/ private_docs/
          # ensure a safe example env
          cp -n .env.example .env.example || true

      # OPTIONAL: Build a clean "public" worktree (no git history rewrite here)
      - name: Prepare publish directory
        run: |
          mkdir _public
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github' \
            ./ _public/

      - name: Push to public repo
        run: |
          cd _public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync public from private: ${GITHUB_SHA}"
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/deniseosoria/education-admin-management-system.git
          git push -f origin main
